language: node_js
script:
- yarn build
notifications:
  slack:
    secure: lKXFaHn4g7fOoGVbibVXpF9HqYKZFzktghlmSr+KhLqwg8OfY9vgkFYnEQKB0ObdWvjSZ24JilVL7BCfIgqp4JDIBSZ+LYJr8azD03guNCyRuSJvbnnJ1WsAFxWRpiQEMaCJ0zYTT54HNuzp1QDEBm2Ymm2Uh3Ixjasrk0/XAQMOiNJKsOMSfm/A4xK+XCl2oOUOkPvJJaGfU9elxwxdXosX3Eta0SFGrqc+GqIi15ix/OhNpRf2BfH4Vkuu3tgqRIyXsnMcTO6uPDF3zPP09ahk2AjpAbLJErD8/PmMvQNgcrMgjPHcuDkOsjkT7+smP5wJbhOmLs24aH4ttEoLy2a15tRZWnsFm9dwlBlVL85TgZLZQkkCusUWsYbJnjtaYb/bmIk2MsBZCKUzUd4mHKK6xeu8I03JzyAu4gEiKl05zOcntyxxezDNWVRakG2x9Qy3elwWvoILhd0+urRnM+mhnK3UfD01gkH7De05Yf+TJMtWKSQANU7xw5xQm1HX4TTMaGi/l6NPKZdGcnSjspePIkr9ufOFmHN2C4PiS4ELvsU1gBywTf1G3NYdK+yYOVk2Blk+8In3JBmBFI1oMfZC1no3ErApyM8DcuuUkZRTKR1mj8zGYT4sGGxwjAx85tNRBzk4TTYp5RN83EmnNrNHz/U6nABBw2GPXGp8cyU=
