version: "3"
services:
  # frontend
  jcm-web:
    container_name: jcm-web
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./docker/jcm-web/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - jcm-api
  # Web API
  jcm-api:
    container_name: jcm-api
    image: ptiringo/japan-commercial-map-api:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - jcm-db
    command: ["./wait-for-it.sh", "postgres:5432", "--", "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jcm-db/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=my-secret-pw
  # DB
  jcm-db:
    container_name: jcm-db
    image: postgres:9.6.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: my-secret-pw